/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        RESULTADO_TXT.setVisible(false);
        textResultado.setVisible(false);
        RESULTADO2_TXT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        textResultado = new javax.swing.JLabel();
        RESULTADO_TXT = new javax.swing.JTextField();
        SOMA_BTN = new javax.swing.JButton();
        SAIR_BTN = new javax.swing.JButton();
        RESTO_BTN1 = new javax.swing.JButton();
        DIVIDIR_BTN2 = new javax.swing.JButton();
        VEZES_BTN3 = new javax.swing.JButton();
        SUBTRACAO_BTN4 = new javax.swing.JButton();
        LIMPAR = new javax.swing.JButton();
        v2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RESULTADO2_TXT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setText("VALOR 1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 100, 220, 30);

        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });
        jPanel1.add(v1);
        v1.setBounds(230, 140, 220, 50);

        textResultado.setText("RESULTADO");
        jPanel1.add(textResultado);
        textResultado.setBounds(300, 320, 80, 30);
        jPanel1.add(RESULTADO_TXT);
        RESULTADO_TXT.setBounds(230, 350, 220, 50);

        SOMA_BTN.setText("+");
        SOMA_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOMA_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SOMA_BTN);
        SOMA_BTN.setBounds(40, 100, 60, 60);

        SAIR_BTN.setText("Sair");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(530, 50, 80, 23);

        RESTO_BTN1.setText("%");
        RESTO_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTO_BTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(RESTO_BTN1);
        RESTO_BTN1.setBounds(40, 383, 60, 60);

        DIVIDIR_BTN2.setText("/");
        DIVIDIR_BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVIDIR_BTN2ActionPerformed(evt);
            }
        });
        jPanel1.add(DIVIDIR_BTN2);
        DIVIDIR_BTN2.setBounds(40, 310, 60, 60);

        VEZES_BTN3.setText("*");
        VEZES_BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEZES_BTN3ActionPerformed(evt);
            }
        });
        jPanel1.add(VEZES_BTN3);
        VEZES_BTN3.setBounds(40, 240, 60, 60);

        SUBTRACAO_BTN4.setText("-");
        SUBTRACAO_BTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBTRACAO_BTN4ActionPerformed(evt);
            }
        });
        jPanel1.add(SUBTRACAO_BTN4);
        SUBTRACAO_BTN4.setBounds(40, 170, 60, 60);

        LIMPAR.setText("Limpar");
        LIMPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPARActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR);
        LIMPAR.setBounds(530, 410, 80, 23);
        jPanel1.add(v2);
        v2.setBounds(230, 260, 220, 50);

        jLabel3.setText("VALOR 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 210, 220, 40);
        jPanel1.add(RESULTADO2_TXT);
        RESULTADO2_TXT.setBounds(250, 420, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(670, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v1ActionPerformed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void SOMA_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOMA_BTNActionPerformed
        Model.Funcoes_DAO.Soma();
    }//GEN-LAST:event_SOMA_BTNActionPerformed

    private void RESTO_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTO_BTN1ActionPerformed
        Model.Funcoes_DAO.Resto();
    }//GEN-LAST:event_RESTO_BTN1ActionPerformed

    private void DIVIDIR_BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVIDIR_BTN2ActionPerformed
        Model.Funcoes_DAO.Divisao();
    }//GEN-LAST:event_DIVIDIR_BTN2ActionPerformed

    private void VEZES_BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEZES_BTN3ActionPerformed
        Model.Funcoes_DAO.Vezes();
    }//GEN-LAST:event_VEZES_BTN3ActionPerformed

    private void SUBTRACAO_BTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBTRACAO_BTN4ActionPerformed
        Model.Funcoes_DAO.Subtracao();
    }//GEN-LAST:event_SUBTRACAO_BTN4ActionPerformed

    private void LIMPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPARActionPerformed
        Model.Funcoes_DAO.Limpar();
    }//GEN-LAST:event_LIMPARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DIVIDIR_BTN2;
    private javax.swing.JButton LIMPAR;
    private javax.swing.JButton RESTO_BTN1;
    public static javax.swing.JLabel RESULTADO2_TXT;
    public static javax.swing.JTextField RESULTADO_TXT;
    private javax.swing.JButton SAIR_BTN;
    private javax.swing.JButton SOMA_BTN;
    private javax.swing.JButton SUBTRACAO_BTN4;
    private javax.swing.JButton VEZES_BTN3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel textResultado;
    public static javax.swing.JTextField v1;
    public static javax.swing.JTextField v2;
    // End of variables declaration//GEN-END:variables
}
