/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        varNome = new javax.swing.JLabel();
        varCaixaTexto = new javax.swing.JTextField();
        varButtonSair = new javax.swing.JButton();
        varButtonMensagem = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 198, 175));
        jPanel1.setLayout(null);

        varNome.setText("NOME");
        jPanel1.add(varNome);
        varNome.setBounds(70, 30, 60, 20);

        varCaixaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCaixaTextoActionPerformed(evt);
            }
        });
        jPanel1.add(varCaixaTexto);
        varCaixaTexto.setBounds(130, 30, 150, 20);

        varButtonSair.setText("Sair");
        varButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(varButtonSair);
        varButtonSair.setBounds(300, 30, 90, 23);

        varButtonMensagem.setText("Mensagem");
        varButtonMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varButtonMensagemActionPerformed(evt);
            }
        });
        jPanel1.add(varButtonMensagem);
        varButtonMensagem.setBounds(240, 220, 130, 23);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/batata-inglesa-unidade.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(260, 120, 100, 100);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(40, 220, 87, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void varCaixaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCaixaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varCaixaTextoActionPerformed

    private void varButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varButtonSairActionPerformed
        model.Mensagem_DAO.exit();
    }//GEN-LAST:event_varButtonSairActionPerformed

    private void varButtonMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varButtonMensagemActionPerformed
        //model.Mensagem_DAO.chama();
        String x = varCaixaTexto.getText();
        JOptionPane.showMessageDialog(null,"O nome digitado foi "+x);
    }//GEN-LAST:event_varButtonMensagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JButton varButtonMensagem;
    private javax.swing.JButton varButtonSair;
    private javax.swing.JTextField varCaixaTexto;
    private javax.swing.JLabel varNome;
    // End of variables declaration//GEN-END:variables
}
